### PR TITLE
Feature/1116 wsdl http bindings

### PR DESCRIPTION
**Pull request by tmandys**
Finished SoapHandler changes. I would merge to devel. There is infinite number of possible changes to support more SOAP features (headerFault, soap:fault etc.).

It requires https://github.com/qorelanguage/qore/pull/1607 merge.

### CODE REVIEW

**Comment by davidnich** [comment]
@tmandys I fixed it but made two API changes

1. I removed the code that allowed SOAP headers to be serialized from the data hash
2. I reverted the change to SoapClient that threw an exception when more than one port was present in the WSDL but no port was explicitly selected in the constructor; in this case the first port is used - this is for backwards-compatibility; the exception broke working code

Also I fixed the WSDL; it was not a valid WSDL according to SoapUI (missing namespace prefixes in various places) - I added more tests.

I'd like to take some more time to review and do some more tests & validations against SoapUI - however what do you think of the changes?  Specifically - is the SOAP header change mentioned above OK from your point of view?

**Comment by omusil24** [comment]
@davidnich Can you please fix the conflicts? I'm not sure if those conflicting parts from develop can be safely removed or should stay there or what.

**Comment by davidnich** [comment]
@tmandys it's ready for your review now - refactoring is done (internal API docs still outstanding), multipart support is disabled since we have no tests for it (and it wasn't working anyway)

**Comment by tmandys** [comment]
Fix is commited and hopefully unit test passed. Have a look.

**Review by davidnich — APPROVED** [review]
IMO it's finally ready for merging

**Pull request merged**
