### PR TITLE
refs #134: Change the reference to make_xml().

### PR DESCRIPTION
**Pull request by geckon**

### CODE REVIEW

**Review by davidnich — APPROVED** [review]

**Comment by davidnich** [comment]
@geckon we need to disable the global weather service test; it's causing jenkins to fail; you fix can't be merged until jenkins passes - can you help?

**Comment by geckon** [comment]
@davidnich I may have some time to look at that during the next days but probably not today.

**Comment by davidnich** [comment]
@geckon ok great - no rush, thank you!

**Comment by geckon** [comment]
GlobalWeather test is disabled now but other tests fail - see issue #138 for more info.

**Comment by geckon** [comment]
Since the tests issues are independent on this small docs change I believe it can be force merged in the same way as #137.
Do you agree, @omusil24?
Thanks.

**Comment by davidnich** [comment]
@geckon I fixed the salesforce tests and also a bug related to qore/qorelanguage#2706, so now it can be merged

**Pull request merged**
